apiVersion: v1
kind: Service
metadata:
  name: {{ imageRepository }}
  labels:
    app.kubernetes.io/name: {{ imageRepository }}
    app.kubernetes.io/managed-by: azure-pipelines
spec:
  type: LoadBalancer
  ports:
  - port: {{ servicePort }}
  selector:
    app.kubernetes.io/name: {{ imageRepository }}